name: Group_26
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - numpy
  - pandas
  - scikit-learn
  - seaborn
  - matplotlib
  - statsmodels
  - jupyterlab
  - ipykernel
  - click
  - quarto
  - requests
  - pip

  - pip:
      - pandera
      - pydantic
